apiVersion: v1
kind: Secret
metadata:
  name: onepassword-sdk-token
stringData:
  token: ENC[AES256_GCM,data:IK194EQQpWRDMJVHxYezLsKWQxuBmLjCjn+OGCRpHnQ+xN7bBrHEaXpyKimVLYq3nhOxaEpL4JCMM/OxWnYhp5gwUyIj1c/XWhn+l8z21BqOhsL+jPyTxyvkRe+uR/mzzpWeqx5ncqFN1QA2OnFMW8bDwwi/jBFOYS1Ehb+9l60v8GHIcL/KY6BzVjUBuxQgAH2ICpfZ/t6hsSAwV9l52Y6KptUZnkGlL9AzvdOC4Ehg/5bBd6+t0Tb7H06Zwz1hLi1t9F9PDRN5zfbTmDtaK0q7nXCJL3RxCS5b4tDAk61A6ZC/2gC0kQI/Pr2casbPBA26SiFYMkt4RqC/WjBoMwG3Q2KyIzE0GwWrC6vcWDI8vniSYtIY+Wiwobih7/HA3o6BLdF3ygAe22XubQcfs0FWKGAk7rVU7rSdzOTYZ7XX8Uwsfo4VF0I3HUvVWk14Gn5S7VzOX73JgNApMLxN1dwyEUmwqqA0hW3KhhiSyyD2n3Q2ntozvBl1FZYKG6s3gCtJ7qw49wAXCW54Pi3Wn+ukhJYdSgXEQeZ35N+7fW1mGqNypyvHsscsAdOULE5jgoj7QGd2pi5Jq7OWf8JAq/OUmCfN6UoxzlI/+A63PVXz+9yYMjXHwNPZLJZXl1KGIxtROVr7WhiTyu0nSZL8K/FrW4H8b8U07tluOXaAK2AnHGpaUffAXGTOwONjnbHC2QbQIti6omzrYCtoeizydcD3fWYszDKa5yXZoCzAi62e4Q5RvOMmux1TskZI6oLdLmgk/Q7q+9V7ljgOQm3QaeP/xT6d3JL7jRU005zd9Eh+MG0RF7raGXlNFwXNkKeZf3iPQBrHy+qf3FxUr5YYhpEA8H/zsiMSR90mgj/bkfODxhAiZEnJpP4KrtE/tn8+Y5oK79MDoVMn28R+AE7LHaegrWJTxGwrUIeCep3QHq8gGQuqRA1xrbSxEDDv6EXp2CP6L0Z4VAi+58H9C8LV9HDdU3Ot2qamkbz0c5ambbRZ0ciV92dJFxbQ8zYrJxoqRMiygL3dhwHcY799izWgX7lowRaA2kdFJ1xCyV9pWfIkM++CxRUEE3v7iu/NPeotmdg=,iv:bA/ScEnfxhP1TeMYo7jk6xDXaiFDREnyIh/2IjjQEOg=,tag:Btz1wKpHTLLamaO3ZIdAmg==,type:str]
sops:
  age:
    - recipient: age1de4xdcq6h5yk4jjyyqe6qws344xsk055rdzvpr79mehvv7q7rdfqnyetjc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHUXJ3cng4Kzk3VWJYQS9j
        Z2RnY1EyY2lMM09ZMWZGcmdqNmozdG1pMVJzCkVTOU53R2xpVWpMZkxRb3dsbU5i
        Z2craW5SUWZXYXIwRExKVDlKY003TTAKLS0tIEpLc0ozOVZrNFFPblRZQy9LTk16
        V1gzcS9ZUGN1VTZMRk1MZVU4dVRkVnMKCNWYwd8IG9hMVwfjuYZiNdNdX7L/Gvw/
        QarR5ahYSiL8IoL2rUqXUuyHvPXfwHDFd5hwuxcLc0wWYWkaZmy7bA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T00:21:32Z"
  mac: ENC[AES256_GCM,data:JJ3858TZtVZdettgRYgVqVvKGTNvztaOHpd27QNAFxAcC9yr++rB+XrYDmcWmKUoTQkKTdJSxrDgosabLqvtfr37Ww8oog0JvhmR+AuprTBXsbmSxYPkgiw+eNVKcS0fBfUePU1YrdklDxFopwy1Oobyz/5fRtDoiVwLsz7AR1o=,iv:GVfT1zmJp5AMz/MjCacLN5GCZOHZOZu0X0epV5Osctk=,tag:aErCyBJPzVYN2yWqi+5RJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
