apiVersion: v1
kind: Secret
metadata:
  name: harbor-admin-secret
stringData:
  adminPassword: ENC[AES256_GCM,data:qqwjrNgbgBWiVpcUgXY7LQDuxMUN7TT//OSKewiqzg==,iv:jrDxS9G9ffF81gFBOceftHxuvs79/TCfOSvn4pDkVeQ=,tag:DUD7DbPW0p6I+COUEclEMQ==,type:str]
sops:
  age:
    - recipient: age1de4xdcq6h5yk4jjyyqe6qws344xsk055rdzvpr79mehvv7q7rdfqnyetjc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJcWZiakVJR2JoMTJuOSto
        WTRjakNPZ0dHb045ZXE2Yi9tbzI1QkZuZG1VCkZJMkExQy8wUVNma2FBakpTY0tv
        U3g0Z0Y2ZHZYR2JjRWRqRTRHRkV4TkkKLS0tIDFSV1pka2l4bmJhbFRYdkV2TjMw
        U25tWm1ocXo2amx5dmVSMmlTdWNIRUkKasfVbNdm608P2k4a/twolz0B7G0CTSRf
        mR5M3KJCBg/33x9TxC36A1qJ4pWpCwbUAxTj7WR5unZmv6x1tZBe1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T22:29:23Z"
  mac: ENC[AES256_GCM,data:MYhvV+x1mtXOzq8wP9AIJxClqueCEYq3j4iFxOTt4z0BqQ/JXtGRyB7XVZa7AqUbPNW3DKH7ziVKv7f3uGFNO9u3I5z41a0eWJOpaXqlDWm9Lpyi0ROUixY817+pBCrK369JeGxWwKRg7ApZz4iNwQgRo2WP7egaatyustJtRrE=,iv:s3ORLe6xeOsYRup2MEbUBj+o/ef4A0yyqO+bo4RVOos=,tag:2n/zM3zq9VEsQKeIxviXjQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
