apiVersion: v1
kind: Secret
metadata:
  name: harbor-admin-secret
stringData:
  adminPassword: ENC[AES256_GCM,data:g8qxUZq/wPGwJ9Bhn2qwnqFOtlwLF22IJWtLyPMvkQ==,iv:WIk30jQqB+rZnZ2914sf7PvUqDEhea4/+xp4Vx8G1y4=,tag:lwU7sszOMQCrfH1OdMvprQ==,type:str]
  externalURL: ENC[AES256_GCM,data:gLn0mt9aLalpjyaCgXqMo0wiLvx9gLb0B/ovmzL1Cmxir97fxh4+,iv:Rm+YbtJBF4qYHGt0NSz/5eZ4V0UA3d9mTRcHYsONRD4=,tag:kmoyzuRp44J9KUJhRk4ZPQ==,type:str]
sops:
  age:
    - recipient: age1de4xdcq6h5yk4jjyyqe6qws344xsk055rdzvpr79mehvv7q7rdfqnyetjc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOWFQNmUxY3ZwZTRRQWtt
        U2p6alh3LzFZTnFKOUU2OXNaNmtmdXczOHljCnlvYUV2SERpbDdBUlE4d0kzMDlM
        aDBJSHI4SWNFb3QwVGJpbit2NTRtemcKLS0tIFhRRmtEV3ZRMFBJa1hMUVNrVmZa
        SzlxRkk4dFN4WnpxY1RLSnhPWkR5RWcKhKA75VQg1n4Q4nOL0gTLImWgeGozmYz4
        C3RDqa8/tzG4nBHzh1qRqQrp7o5SjQlw1INA+W8M3CnX6k9daEF3eQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-02T22:56:35Z"
  mac: ENC[AES256_GCM,data:m3mz3t2YhIVUriufg+jXRDGfzZe4HU1PqnAYQRt/ZqwbyLmNCECRWlcjiQgHWFnuQvt69HJOXTxzGmwqJjIslCf2u7iUaELKvg1fvO/bkk7hbS3Ue6OFJWd0QlVM2eS+S8wy75/xoonjupC7s48/u9SL3iF/IrnoYm1nLJGTiKM=,iv:PqNFGNjGLuGPLglB93bLCxGthrxOoWHtqlrzHAzDlCY=,tag:01UKai1yyL1l/PHqo4IUgg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
