apiVersion: v1
kind: Secret
metadata:
  name: harbor-admin-secret
stringData:
  adminPassword: ENC[AES256_GCM,data:g8qxUZq/wPGwJ9Bhn2qwnqFOtlwLF22IJWtLyPMvkQ==,iv:WIk30jQqB+rZnZ2914sf7PvUqDEhea4/+xp4Vx8G1y4=,tag:lwU7sszOMQCrfH1OdMvprQ==,type:str]
sops:
  age:
    - recipient: age1de4xdcq6h5yk4jjyyqe6qws344xsk055rdzvpr79mehvv7q7rdfqnyetjc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOWFQNmUxY3ZwZTRRQWtt
        U2p6alh3LzFZTnFKOUU2OXNaNmtmdXczOHljCnlvYUV2SERpbDdBUlE4d0kzMDlM
        aDBJSHI4SWNFb3QwVGJpbit2NTRtemcKLS0tIFhRRmtEV3ZRMFBJa1hMUVNrVmZa
        SzlxRkk4dFN4WnpxY1RLSnhPWkR5RWcKhKA75VQg1n4Q4nOL0gTLImWgeGozmYz4
        C3RDqa8/tzG4nBHzh1qRqQrp7o5SjQlw1INA+W8M3CnX6k9daEF3eQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-11T18:29:13Z"
  mac: ENC[AES256_GCM,data:j/FBNcqIP+iKAsZKDRbTTjKs6lX8OWKnNcth+GmVj+LM7Mpj6v+MSjuqG4S01+CZm6QgwPfQ7XDt0m//foZi4cFGqRwJL31Iri9SREqdVeLpI1eC1ayDZ0FKB4XA8WHKcZG/a4yAWbAaR11Aafc+Md6eKFgf9jmxARthNS0c9ro=,iv:Eyl8hHS92L59RgKvAlmLEnyt93bUz4fhNT9C29UTYUo=,tag:dX+njyOuKORBKT8tuZwxHw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
