apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:yRdVnGh699gCeQ==,iv:q8eRaxGR4wCr5laay5W6sPSag92m2BWFcT9chKIbNtE=,tag:Bp2VOR6cveQVJPxnmgbNEg==,type:str]
  SECRET_DOMAIN_TWO: ENC[AES256_GCM,data:XKk/42xxWL0OWo4VCN5DW4a8Tthz1yjS,iv:XmQYwRxj7Y8+/43P5IWFb5Ntcc6LD3VvKmZT8s7nb0I=,tag:+YiAtIR4YwDdA5CuCQxyYA==,type:str]
sops:
  age:
    - recipient: age1de4xdcq6h5yk4jjyyqe6qws344xsk055rdzvpr79mehvv7q7rdfqnyetjc
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZkdmYjE0VXVWdFhPTjJG
        N0pOUUh6MmdCRGNZL2RZMU5zNmVRSFYvNWt3CnhPN3R1VEZIUmVXSldrZFVCU3Fi
        YmE2WTUyY1gwSXZ1MkJENkVBOVZkb2MKLS0tIFhjQXpNeDhQV29yMEg3Tm1Rc3Vi
        VmhTY3lVK1RzVS9WVlVmcUg2TlVCYzgKwylgNY7OnZbFcy4XePRsYouW4Cec/kud
        OX7hYT/0SEVsSOy2jUJoYpQ/FVuu2bH79Hro/7l1WxwIZsB8ytBkng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-12T00:10:21Z"
  mac: ENC[AES256_GCM,data:I/r+Ncl6B0igxK3okaNi8qA/p99N0ZG6dghg40dj3waqQfRewzud/PELbKVifeWSWv6V2AHu3B4glKik8qTrcx8mmao1FlUp+NPeaNpdgEVaVeWJsvAtsDAN2TMVaaIpz60Rx+U2liqEzh3bkOlsfZLp7qnKVJH7SzcCzGXf98g=,iv:rC7dmlZ23tQT+dV4qV3Cp5M7vvE2uFstRZI/tjrcFDA=,tag:vheTVjajXzNjc3193mjU7A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
