---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harbor
components:
  - ../../components/sops
resources:
  - ./namespace.yaml
  - ./harbor-postgres/ks.yaml
  - ./harbor-redis/ks.yaml
  - ./harbor/ks.yaml
