---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor-postgres
spec:
  interval: 1h
  path: ./kubernetes/apps/harbor/harbor-postgres/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: harbor
  wait: true
  # WHY: PostgreSQL must be ready before Harbor attempts to connect
  dependsOn:
    - name: cloudnative-pg
      namespace: databases
