---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: harbor-redis
spec:
  interval: 1h
  path: ./kubernetes/apps/harbor/harbor-redis/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: harbor
  wait: true
  # WHY: DragonflyDB operator must be running to create Dragonfly resources
  dependsOn:
    - name: dragonfly-operator
      namespace: databases
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
